name: app_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  flare_splash_screen: ^3.0.1
  flare_flutter: ^2.0.6
  argon_buttons_flutter: ^1.0.6
  flutter_spinkit: ^4.1.2+1
  animated_text_kit: ^2.2.0
  font_awesome_flutter: ^8.8.1
  flutter_signin_button: ^1.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase: ^7.3.0
  firebase_analytics: ^6.0.0
  cloud_firestore: ^0.14.0+2
  intl_phone_number_input: ^0.5.1
  rflutter_alert: ^1.0.3
  pin_code_fields: ^5.0.1
  form_field_validator: ^1.0.1
  google_sign_in: ^4.5.3
  flutter_auth_buttons: ^0.10.0
  flutter_facebook_login: ^3.0.0
  http: ^0.12.2
  modal_progress_hud: ^0.1.3
  simple_animations: ^2.2.1
  shared_preferences: ^0.5.12
  auto_size_text: ^2.1.0
  lottie: ^0.6.0
  mailer: ^3.0.4
  date_format: ^1.0.8
  flutter_hooks: ^0.14.0
  synchronized: ^2.2.0+2
  dynamic_theme: ^1.0.1
  foldable_sidebar: ^1.0.0
  swipedetector: ^1.2.0
  easy_localization: ^2.3.3
  flutter_staggered_animations: ^0.1.2
  clay_containers: ^0.2.2
  connectivity: ^0.4.9+2
  dropdownfield: ^1.0.3
  date_field: ^0.3.2
  edge_alert: ^0.0.1
  image_picker: ^0.6.7+9
  dropdown_formfield: ^0.1.3
  multi_image_picker: ^4.7.14
  firebase_storage: ^4.0.0
  dropdown_search: ^0.4.4
  flutter_swiper: ^1.1.6
  smooth_star_rating: ^1.1.1
  flutter_custom_dialog: ^1.0.20
  cached_network_image: ^2.0.0
  search_widget: ^1.0.2
  fancy_bottom_navigation: ^0.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - languages/langs/en-US.json
    - languages/langs/ar-EG.json
    - languages/langs/de-DE.json
    - languages/langs/it-IT.json
    - languages/langs/fr-FR.json
  fonts:
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico-Regular.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
